# Introduction to Pytorch Neural Network

Welcome to the third day of the pool. In this part you will learn how to build neural networks using Pytorch.


You've already learned how to create a neural networks from scratch, this involves digging deep down in math and and is quite complex at some levels.
In this exercise you will learn to fly by all the complexity of AI by using the Pytorch library.

Pytorch is a Python library used to create simple or complex AI as fast and efficient as possible.


The first step will be to install and import the library.

In [12]:
!pip3 install torch

import torch

### Introduction to Pytorch and tensor

Our first part will be to learn about Tensor and learn to use them. A Tensor is a multi-dimensional matrix containing any numerical value. We can see a tensor like a multi-dimensional array, it can have any shape.


**Exercise :**\
Create a tensor containing  only ones, the tensor must have a shape of ``[3, 3]``.

In [4]:
# use ones fonction of Pytorch librairie.
torch.ones([3,3])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

**Expected result :**
`tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])`

Now that you can create a tensor, let's try to do some simple math with it.

**Exercise :**\
Create a tensor containing only ones, the tensor must have a shape of ``[3, 3]`` and find a way to multiply ``constant`` with the tensor.

In [5]:
constant = 5

tensor = torch.ones([3,3])

tensor * constant

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])

**Expected result :**
`tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])`

The last thing we need to learn, is the ability to change the shape of the tensor.

**Exercise :**\
Create a tensor containing  only ones, the tensor must have a shape of ``[3, 9]`` and reshape the tensor to a shape of ``[3, 3, 3]``

In [6]:
tensor = torch.ones((3, 9), dtype=torch.float)
# print(tensor)
# reshape the tensor
tensor.reshape([3,3,3])

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

**Expected :**\
``tensor([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],
        [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],
        [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])``

### Getting the data for the AI

Now that you saw how easy it easy to create, and transform a tensor we can start creating an AI.

From now on, our goal is going to create a simple AI whose purpose is to predict multiple of 2. For exemple, if the input is 5 the output should be 10 (or close enough).

We must first start by create a function to get data to train and test our AI.

**Exercise :**\
Create a function called `getData` which takes in two parameters `start` and `end`. The function must return a tendor (of shape `[n, 1]` with `n` equal to the number of interger) containing every interger between `start` (inclusive) and `end` (exclusive).

In [20]:
def getData(start=0, end=200):
    # use arange fonction of Pytorch librairie.
    tensor = torch.arange(start, end, dtype=torch.float)
    tensor = torch.reshape(tensor, [end, 1])
    return tensor

data = getData(0, 10)

print(data)
print(data.shape)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
torch.Size([10, 1])


**Expected :**\
`tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])`\
`torch.Size([10, 1])`

We now have data for the input of the AI, but we need to compare the output data against the real expected result to compare both value and get the loss.

**Exercise :**\
Create a function called `calcExpected` which takes one parameter `tensor`. The function must return a tensor where each value has been double.

In [21]:
def calcExpected(tensor):
    # multiply the tensor by 2
    return tensor * 2

data = getData(0, 10)
calcExpected(data)

tensor([[ 0.],
        [ 2.],
        [ 4.],
        [ 6.],
        [ 8.],
        [10.],
        [12.],
        [14.],
        [16.],
        [18.]])

**Expected :**\
`tensor([[ 0.],
        [ 2.],
        [ 4.],
        [ 6.],
        [ 8.],
        [10.],
        [12.],
        [14.],
        [16.],
        [18.]])`

### Buld a Pytorch neural network

Well done !

Now that we have all our data, to train and test our AI, let's actually create it.
I'm going to show you the simpliest model you can create as an exemple:

In [22]:
class ExempleNetwork(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = torch.nn.Linear(1, 2) # First layer, it takes one number and output two number
        self.linear2 = torch.nn.Linear(2, 1) # Second layer, it takes two number and output one number
        
    def forward(self, x):
        x = self.linear1(x)             # Applies the first layer to the data
        x = torch.nn.functional.relu(x) # Activation function
        x = self.linear2(x)             # Applies the second layer to the data
        x = torch.nn.functional.relu(x) # Activation function
        return x

network = ExempleNetwork()

As you can see it's quite staight forward, we start by creating each layer of our AI (in this exemple, two layers are created), and we create a forward function to apply each layer with activation function after each layer.

ReLU is an activation which looks like:
<div>
    <!-- <center> -->
    <img src="../.img/ReLU.png" width="300" style="padding-left: 20px;"/>
    <!-- </center> -->
</div>

Let's test to see if our model works

In [23]:
data = getData(0, 1)
network.forward(data[0])

tensor([0.1629], grad_fn=<ReluBackward0>)

**Expected :** No particular value is expected because it is a random output

### Your turn

Now that you have an exemple of how Pytorch AI models are constructed, it's your turn to create your own AI.

**Exercise :** Create a AI model, which must take one number as input and output one number. You can create as much layers as you want.

In [30]:
class MyNetwork(torch.nn.Module):
    def __init__(self):
        super().__init__()
        # create your layers
        self.linear1 = torch.nn.Linear(1, 2) # First layer, it takes one number and output two number
        self.linear2 = torch.nn.Linear(2, 1) # Second layer, it takes two number and output one number
        
    def forward(self, x):
        # apply each layer with a activation function
        x = self.linear1(x)             # Applies the first layer to the data
        x = self.linear2(x)
        return x

network = MyNetwork()

In [31]:
data = getData(0, 1)
network.forward(data[0])

tensor([-0.4308], grad_fn=<AddBackward0>)

**Expected :** No particular value is expected because it is a random output

Before combining everyhting we've learn, we need to declare a loss function, and a optimizer. There is a vast amount amount of loss function and optimizer..

An optimizer is gonna let us apply the gradiant on the model. The optimizer is comprised of a algorithm to apply the gradients. The algorithm that we are going to use is Adam. (for more information, check the following link: <a>https://pytorch.org/docs/stable/generated/torch.optim.Adam.html#torch.optim.Adam</a>

For the loss function, the task we are trying to solve is a regression problem, thus the mean squared error function is a good choice, its formula is:

$$\begin{align*} & Loss(\hat{y},y) = \sum_{i=0}^m(y^{(i)} - \hat{y}^{(i)})^2 \end{align*}\tag{7}$$

In [32]:
LR = 0.01

mse = torch.nn.MSELoss() # Loss function
optimizer = torch.optim.Adam(network.parameters(), lr=LR) # Optimizer

We now have all the elements to train and test our AI.

To summarize every element we've created:

    - Create the model of our AI, and create a forward function to get the AI's prediction.
    - Chose and initialize a loss function adapted to the goal of our task.
    - Chose and initialize a optimizer to apply the gradients to improve the AI.


Let's start by training our AI, we will first load our data.

(The next code cell is already completed, but read the comments carefully to make sure everything is clear)

## Training

In [33]:
EPOCH = 2
data = getData(0, 1001) # get our training data

for j in range(EPOCH):
    for i in range(len(data)):
        output = network.forward(data[i]) # Forward pass
        loss = mse(output, calcExpected(data[i]))
        loss.backward() # Calculating each gradient
        optimizer.step() # Apply each gradient
        optimizer.zero_grad() # Reset gradient to zero
        if (i % 10 == 0):
            print(loss) # Print the loss every 10 cycle

/mnt/nfs/homes/lboukrou/.local/lib/python3.8/site-packages/torch/autograd/__init__.py:154: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:112.)
  Variable._execution_engine.run_backward(


tensor(0.1856, grad_fn=<MseLossBackward0>)
tensor(508.0105, grad_fn=<MseLossBackward0>)
tensor(1667.3236, grad_fn=<MseLossBackward0>)
tensor(2957.3418, grad_fn=<MseLossBackward0>)
tensor(3901.2468, grad_fn=<MseLossBackward0>)
tensor(4115.8560, grad_fn=<MseLossBackward0>)
tensor(3239.9404, grad_fn=<MseLossBackward0>)
tensor(1351.2170, grad_fn=<MseLossBackward0>)
tensor(33.0279, grad_fn=<MseLossBackward0>)
tensor(187.1589, grad_fn=<MseLossBackward0>)
tensor(11.8963, grad_fn=<MseLossBackward0>)
tensor(32.8925, grad_fn=<MseLossBackward0>)
tensor(0.2900, grad_fn=<MseLossBackward0>)
tensor(2.3375, grad_fn=<MseLossBackward0>)
tensor(1.9715, grad_fn=<MseLossBackward0>)
tensor(0.6071, grad_fn=<MseLossBackward0>)
tensor(0.2041, grad_fn=<MseLossBackward0>)
tensor(0.0686, grad_fn=<MseLossBackward0>)
tensor(0.0400, grad_fn=<MseLossBackward0>)
tensor(0.0118, grad_fn=<MseLossBackward0>)
tensor(0.0017, grad_fn=<MseLossBackward0>)
tensor(0.0009, grad_fn=<MseLossBackward0>)
tensor(0.0004, grad_fn=<MseLo

tensor(0.0028, grad_fn=<MseLossBackward0>)
tensor(1.2532e-05, grad_fn=<MseLossBackward0>)
tensor(5.3644e-05, grad_fn=<MseLossBackward0>)
tensor(0.0008, grad_fn=<MseLossBackward0>)
tensor(0.0462, grad_fn=<MseLossBackward0>)
tensor(48.3493, grad_fn=<MseLossBackward0>)


## Testing

After training our AI, let's test its accuracy on new data which the AI hasn't been trained on.

(The next code cell is already completed, but read the comments carefully to make sure everything is clear)

In [ ]:
data = getData(2000, 2101) # get our testing data
for i in range(len(data)):
    output = network.forward(data[i]) # Forward pass
    print('Prediction %.2f, Expected %.2f' % (output.item(), calcExpected(data[i]).item()))

**Expected :** The prediction of the AI must be close to the expected value, if the difference between the prediction and expected is higher than 5, try to improve your AI model.

# Congratz

Congratulations for having reached the end of this workshop !\
You have been able to create your own AI using Pytorch.\
During this day, you'll have the chance to create a more complex AI with the fundamental you've just learned.

See you for the next topic!